services:
  koesu:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - lavalink
      - redis
    ports:
      - "${RPC_PORT:-3000}:3000"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    restart: unless-stopped
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins:/opt/Lavalink/plugins
    ports:
      - "2333:2333"
    depends_on:
      - redis

volumes:
  redis_data:
